"""Rename is_completed field to status field

Revision ID: 674d2b9f7aae
Revises: 5c1404966871
Create Date: 2025-02-01 23:45:24.865545

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "674d2b9f7aae"
down_revision: Union[str, None] = "5c1404966871"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks",
        sa.Column(
            "status",
            sa.Enum("ongoing", "completed", "overdue", name="taskstatus"),
            server_default="ongoing",
            nullable=False,
        ),
    )
    op.drop_column("tasks", "is_completed")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks", sa.Column("is_completed", sa.BOOLEAN(), nullable=False)
    )
    op.drop_column("tasks", "status")
    # ### end Alembic commands ###
