"""Add owner_id and tasks between User and Task models

Revision ID: 90ba490235bc
Revises: 941dab569212
Create Date: 2025-02-22 21:25:21.453141

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "90ba490235bc"
down_revision: Union[str, None] = "941dab569212"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks') as batch_op:
        batch_op.add_column(sa.Column("owner_id", sa.String(), nullable=True))
        batch_op.create_foreign_key(
            "fk_tasks_owner_id", "users", ["owner_id"], ["id"], ondelete="CASCADE"
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tasks", type_="foreignkey")
    op.drop_column("tasks", "owner_id")
    # ### end Alembic commands ###
