"""Add owner_id and tags between User and Tag models

Revision ID: fee5bebd5129
Revises: 90ba490235bc
Create Date: 2025-02-23 20:10:10.519743

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fee5bebd5129"
down_revision: Union[str, None] = "90ba490235bc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tags", sa.Column("owner_id", sa.String(), nullable=True))
    op.create_foreign_key(
        None, "tags", "users", ["owner_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tags", type_="foreignkey")
    op.drop_column("tags", "owner_id")
    # ### end Alembic commands ###
